### ISSUE TITLE
Integrating Devise with Wunderschön for User & Admin Account System

### ISSUE THREAD

**Issue by Maxwell-Alexius** [Maxwell-Alexius/Wunderschon#18]

**Comment by Maxwell-Alexius** [comment]
機器人認證參考：
https://github.com/ambethia/recaptcha

**Comment by akiicat** [comment]
`sign_in` and `sign_up` in one page

**Comment by Maxwell-Alexius** [comment]
Closed with PR #75 Merged;

Other similar issues such as the admin system or other permission management should open and resolve in another issue.
