### ISSUE TITLE
Product UI Design

### ISSUE THREAD

**Issue by puppy2017** [Maxwell-Alexius/Wunderschon#28]
![max_t _2](https://user-images.githubusercontent.com/25365833/26860724-1d02e7de-4b72-11e7-9139-d3394e60e743.jpg)
![max_t _1](https://user-images.githubusercontent.com/25365833/26860726-1d47a568-4b72-11e7-84be-09fadf3e082a.jpg)

**Comment by Maxwell-Alexius** [comment]
This issue aims for designing the details of the product UI including the:
`CategoriesController#show` and `ProductsController#show page`

**Comment by Maxwell-Alexius** [comment]
Closed with PR #62 Merged
